### ISSUE TITLE
Intergrate NeoFS node with oracle support

### ISSUE THREAD

**Issue by roman-khimov** [NeoResearch/neocompiler-eco#108]
NeoFS should be configured with mainnet support (so plain AIO doesn't work) and oracles should be configured to allow fetching data from it. We can use the simplest config with a single IR and a single SN. Gateways and FS object management are out of scope at the moment, we can just put some sample objects into it for the beginning. Oracle example can be extended with some NeoFS-specific method.

**Comment by vncoelho** [comment]
Sure, @roman-khimov 

In relation to mainnet why do we need to provide IR and single SN? Isn't it already estabilished and we just interact with?

For its shared privatenet (Personalized) I think that we need that.
Anyway, count with me for integrating it.

**Comment by roman-khimov** [comment]
By "mainnet" I mean private network that is used by NeoCompiler. It's just that NeoFS has some modes, it can run standalone and it can be attached to some "mainnet" network with "mainnet" being any kind of network, not necessarily the mainnet (860833102).

@evgeniiz321 will try doing this once he deals with other current issues.

**Comment by vncoelho** [comment]
I understand now! Perfect.

This is something we really want to implement here. Count with us in any need.
