### ISSUE TITLE
Magic boxes for invoke

### ISSUE THREAD

**Issue by igormcoelho** [NeoResearch/neocompiler-eco#13]
Folks, we need to implement "magic box" feature, based on abi information, so we can invoke contract functions directly from a listbox, and filtering parameters correctly (strings, numbers, lists...). I believe this feature should also indicate a json format for passing invoke infomation (perhaps we propose a NEP for this?).

**Comment by vncoelho** [comment]
Magic, literally! Very gud, ma broda
