### ISSUE TITLE
Add NEP-2 string wallet import feature

### ISSUE THREAD

**Issue by igormcoelho** [NeoResearch/neocompiler-eco#17]
Add feature to import NEP-2 wallet (client-only!!) and perform invoke operations on private/testnets. It is important to NEVER store or print this value anywhere (on backend), and also warn that is very dangerous to use mainnet wallets here.

**Comment by igormcoelho** [comment]
I believe we can have 3 input modes for wallets: Address base58 (watch only), publickey (watch only, but we also calculate Address and have two infos), NEP-2 (we have all information and can operate with wallet in testnet/privatenet with neon-js, not python). These can be added in Utils.

**Comment by igormcoelho** [comment]
@ftgibran

**Comment by vncoelho** [comment]
As well as include wallets by hand at the vector of known wallets.
After that, change to `NeoLink`

**Comment by vncoelho** [comment]
This has been partially accomplished throught #b875717
