### ISSUE TITLE
File Sharing issues when installing NeoCompiler on MacOS

### ISSUE THREAD

**Issue by tomascarvalho** [NeoResearch/neocompiler-eco#25]
**Issue:** Running the `./build_everything.sh` shell script on mac os will result in error. Docker tries to use file sharing with a folder that does not exist on MacOS `/var/logs/`, raising an error and aborting the shell script. This can possible be fixed by meddling with Docker for Mac File Sharing properties, but I was not able to do it .

**Possible Solution:**  Change the path in order to work in other OS's.

I got it working by creating a folder called `dkr`at my home directory and changed every `/var/log/` occurrence **in the project** to `~/dkr/`.

https://github.com/NeoResearch/neocompiler-eco/blob/c6299893590f78fc104b426c008c0bbb3648460e/dockers-neo-scan-neon/docker-neo-scan/docker-compose.yml#L23-L26

**Comment by igormcoelho** [comment]
You are correct, let's put a local directory near `docker-compose.yml`file.
