### ISSUE TITLE
[Bug] AVM Decompiler not working for hex files

### ISSUE THREAD

**Issue by lock9** [NeoResearch/neocompiler-eco#28]
Hello,
I'm using https://neocompiler.io/#/ecolab to understand a few scripts better, and it works great. The problem is that if I want to upload my own .avm file in HEX format, it doesn't work.
It's not a problem with my code, but with the editor itself, since if I download and upload the avm from the editor, it also doesn't work.
Maybe @ftgibran  can help us?  👍

**Comment by igormcoelho** [comment]
HI @lock9 , the avm upload feature expects "binary" format (which is usually generated by all compilers, boa, neon, ...), not hexstring format.
But I'm gonna test it again anyway, something may have corrupted this feature recently.
