### ISSUE TITLE
Always response with status of  "Fault, Break"

### ISSUE THREAD

**Issue by rct1985** [NeoResearch/neocompiler-eco#31]
It's realy a nice website of "https://neocompiler.io", and it saves me hours for test smart contracts.
But when i deploy a simple smart contracts directly on your website, and test it with "postman". it always responses with status of "Fault, Break".
The avm file works well on my local neopy prompt. 
Any advice is appreciated.

**Comment by igormcoelho** [comment]
Hi @rct1985 , that's strange because yesterday I tested many smart contracts there... have you tried invoking it using neo-python invoke on the website? the syntax is the same from local python.

**Comment by rct1985** [comment]
# It works today
Thanks for your reponse, and it works today . 
In china, We connect to your website according vpn, May be there was something wrong with my network. 
# Another question
I want to check content of special key in the storage, but sometimes I get "contract exists!" in the output field. Somtime it works and i can getting the correct content. it really confuses me

Thanks in advance!

**Comment by igormcoelho** [comment]
Yeah, the intention of the message is to say "You contract exists, but key does not". Many people try to get storage from an "undeployed" contract, what confuses people even more (that's why we put this message).

**Comment by igormcoelho** [comment]
Improved message: https://github.com/NeoResearch/neocompiler-eco/commit/893a3e5b4b305fa52089c218f2a59b0ab672a9b4

**Comment by rct1985** [comment]
Got it
thanks for your imporment
