### ISSUE TITLE
Need your help, wallets is unavailable sometimes

### ISSUE THREAD

**Issue by rct1985** [NeoResearch/neocompiler-eco#35]
I found the wallets in the neocompiler.io is unavailble sometime recently. 

I want to show our dapp demo in 4 August in Game-Shared meeting organised by offical of neo. Would you help me to make neocompiler.io stable in that day.
I would like to introduce the neocompile.io to other developers in that meeting.

thank you in advance.

**Comment by igormcoelho** [comment]
The best option is always to have a local instance of neocompiler.io (just clone neocompiler-eco and execute `./build_everything.sh`). But I agree it's very nice to have a fully working online platform. So, to help you out we will put the platform online without any resets until August 5th. I will just make some adjustments for greater stability, and let you know when it's fully online (if you want to have some Neo locked for you during this period, send me your address and we will put a part of the privatenet neo on your hands to generate privatenet gas for you guys :D).

**Comment by igormcoelho** [comment]
Waiting for the address ;)

**Comment by rct1985** [comment]
Thanks . It's very helpful advice for me, and I will try.
I was very appreciated to introduce your project to other developers in that meeting. 
And it's the picture .
[picture in meeting](http://www.imageurl.ir/images/38759461280119453290.jpg)
