### ISSUE TITLE
"Unknown Compiler!" error when a compiler other than C# compiler

### ISSUE THREAD

**Issue by tomascarvalho** [NeoResearch/neocompiler-eco#36]
I get a  `Unknown Compiler! Please use something from the list!` error when trying to use a compiler (Python, Go, Java) other than the C# compiler.

**Comment by vncoelho** [comment]
Sorry for this, we needed to double check the security because of the new option of multiple compilers. Perhaps something wrong for the other compilers. Soon we will fix it.

Thanks,

**Comment by igormcoelho** [comment]
Vitor, I guess we need a list like that for all compilers... then we submit the type of compilation "csharp", or "python", together with the compiler version.

**Comment by vncoelho** [comment]
Done as suggest by Igor. Thanks to both of you,
