### ISSUE TITLE
Deploy complains of contract not being deployed yet (wat???)

### ISSUE THREAD

**Issue by igormcoelho** [NeoResearch/neocompiler-eco#37]
There's a recursive behavior on "Deploy", because it complains contract is not deployed yet xD hahaha but it works anyway... 3 commits to get 1000, do we need a cake? :)

**Comment by vncoelho** [comment]
We need! I think we gonna celebrate 1M visits and the commits all together :package: 

this issue was fixed with an if verification :dagger:
