### ISSUE TITLE
dotnet Dockerfile can be largely simplified

### ISSUE THREAD

**Issue by nunojusto** [NeoResearch/neocompiler-eco#39]
https://github.com/NeoResearch/neocompiler-eco/blob/master/docker-ubuntu-dotnet/Dockerfile
This Dockerfile is installing all by hand.

Why not use the official Microsoft ubuntu release docker image?
https://hub.docker.com/r/microsoft/dotnet/
With this you can have all the updates done by them in the official way.

Also, if this is only to run csharp stuff already compiled (published) you don't need SDK, you can use the dotnet runtime.

**Comment by vncoelho** [comment]
Let's make some experiments. It may simplify our scripts and reduce image size (can also make things faster).

Thanks for suggesting.
