### ISSUE TITLE
Add F# compiler support

### ISSUE THREAD

**Issue by wschae** [NeoResearch/neocompiler-eco#44]
Let us support F# compiler. 
I will add a few simple F# examples here.
If the team needs any help for test, let me know :)

**Comment by igormcoelho** [comment]
Man, the idea is great!
I tried to give a first push here: https://github.com/NeoResearch/neof

Took some days to understand basic F# and slightly change basic neon C# compiler to at least generate any avm! :)
By the way, I didn't test the output yet, it is probably not fully working... but like I told you on DevCon, it could be medium or hard challenge, now I'm confident it's easy to medium, which is awesome.

I'll close this one, but let's keep talking ;)
