### ISSUE TITLE
Deploy Error: One of the policy filters failed

### ISSUE THREAD

**Issue by saltyskip** [NeoResearch/neocompiler-eco#45]
When attempting to compile and deploy the ICO contract template on the C# template, the contract compiles fine and generates the avm, but when I try to deploy it in the next step I get this error

![image](https://user-images.githubusercontent.com/14796429/53467217-96be3a80-3a98-11e9-9157-0044adefa956.png)

**Comment by saltyskip** [comment]
After talking with @igormcoelho on discord, I see that transaction is too large and requires a network fee. It would be nice if the error in this case was more specific

**Comment by vncoelho** [comment]
In fact the error was even less specific...aehuaheauea
It was just saying failed as reason. In fact, this message comes from the c# neo-cli RPC.

We improved it here https://github.com/neo-project/neo/commit/ff174f79d72065c2f772d062e82f0235d4d2efaa

In the future we can try to pass the reason that the plugin denied that.

**Comment by igormcoelho** [comment]
This problem is hard to detect, you are right, we need something to help us here. Soon, I'll try to pre-calculate tx size based on contract size, so we know how much to expect for network fee and we can automatically fill the box with the value.

**Comment by igormcoelho** [comment]
Let's create a box on "Conversors/Tools" tab to calculate tx fee.
At this section, we can have a deploy transaction box with avm hex, and it pre-calculate the expected size (witness, parameters, etc).

**Comment by vncoelho** [comment]
It is now calculated automatically when a contract is compiled.
Maybe still need to check this when AVM is upload.
