### ISSUE TITLE
Claim Fails Error, even though Claim is Successful

### ISSUE THREAD

**Issue by saltyskip** [NeoResearch/neocompiler-eco#47]
When I click orange claim button here for the top address

![image](https://user-images.githubusercontent.com/14796429/53471022-be1c0400-3aa6-11e9-81e5-ae23c12a7962.png)

I recieve the following error

![image](https://user-images.githubusercontent.com/14796429/53471002-ac3a6100-3aa6-11e9-8e6c-d16f6932bad4.png)

However if I wait a few moment it seems that the claim is successful, and the GAS is successfully transferred into the wallet

**Comment by vncoelho** [comment]
There is an automatic script that claims everything in all registered addresses.
Sometimes it lags until neoscan process the last block, in this sense, your front-end tries to claim again and results in this error =/ However, it is just a minor message. :P aehuaheua

**Comment by saltyskip** [comment]
I see, if one button claims everything I think it might be easier to understand if there is only one button. This would make it clear that I am actually performing multiple claims at once

**Comment by vncoelho** [comment]
Anhhhhh, the button is for each address.
But, for example, since claim is two steps, if someone had made any transfer and the claim is pending and that address is shared, then, anyone that enters in the website will claim it.

**Comment by igormcoelho** [comment]
I agree that sometimes these messages are just excessive hahaha perhaps we need better UI (a red color on claim address when it fails, I don't know), but something better than constantly pop-up messages. Often I turn off the notifications, to avoid these things, which is clearly not the best usage of the system. Let's think and try to improve that.

**Comment by vncoelho** [comment]
@saltyskip, I will leave this closed because it is due to multiple request as we are trying to solve on #49. But fell free to open if there is still something strange.
