### ISSUE TITLE
Make Return Types and Deploy Params More obvious

### ISSUE THREAD

**Issue by saltyskip** [NeoResearch/neocompiler-eco#48]
![image](https://user-images.githubusercontent.com/14796429/53538729-3be91980-3b52-11e9-9703-beddee46d3bb.png)

Currently it has the raw integer values, and it is not possible to know what this translates to (String, Int, etc.)

It would be nice to show the type in plain text format instead of the hex code

**Comment by igormcoelho** [comment]
This is what happens when you work with nerds hahahah you're right, we will fix that soon enough ;)

**Comment by vncoelho** [comment]
@saltyskip and @igormcoelho, should we let both:
* ff - void
* 02 - string
* 04 - beer
etc

Or just the type?

**Comment by saltyskip** [comment]
+1 for both

**Comment by vncoelho** [comment]
Done, thanks @saltyskip.
