### ISSUE TITLE
Too many repeated calls to node

### ISSUE THREAD

**Issue by saltyskip** [NeoResearch/neocompiler-eco#49]
https://cl.ly/4dce9b3b8030

It looks like neocompiler continually retrys transactions if they fail. I think it is putting unnecessary stress on a node, and causing errors

**Comment by vncoelho** [comment]
You are right, we need to check direct in the rpc before making such claim calls, the neoscan takes time to sync.

**Comment by igormcoelho** [comment]
Oh man, this code was meant for use as a Denial of Service xD self-destructing our servers!

**Comment by vncoelho** [comment]
This commit here improved that a little bit: https://github.com/NeoResearch/neocompiler-eco/commit/8434a6ed063db91b106dc4f1dcdb97b4eb58619e

But it is just a workaround until we do not track UTXO and Claimable direct from neocli.

**Comment by vncoelho** [comment]
Andrei, automatic node selection based on best height is now working as well! 
If experience any problem let us know :dancer: 
https://github.com/NeoResearch/neocompiler-eco/commit/c962f7a38880369271a0179f59258ac946ae15dd

**Comment by vncoelho** [comment]
![image](https://user-images.githubusercontent.com/17395762/54057422-b01a6180-41d1-11e9-80d5-26654abcba4a.png)

**Comment by vncoelho** [comment]
![image](https://user-images.githubusercontent.com/17395762/54057593-2919b900-41d2-11e9-9c04-36e5de893ed2.png)

**Comment by saltyskip** [comment]
Looks good, one more suggestion I have is filtering neo.org nodes (on the testnet) from the node list programmatically, they appear to not be playing nicely recently. It is better to use the NGD nodes for stability. Or allow for a custom node selection override

**Comment by vncoelho** [comment]
Sounds good. Currently the first input in the config can be modified and the selection box has a fixed list.

Maybe we can also allow upload of a specific list, do you think it is usefull?

**Comment by vncoelho** [comment]
It should be almost solved now with https://github.com/NeoResearch/neocompiler-eco/commit/ccfe45ba819009a4d36978d6be0dbfaa9ed8b05b

If you experience problems with multiple calls again please open a new issue or re-open this one, there are still some minor things to improve. :dancer:
