### ISSUE TITLE
Calculate ScriptHash / Address / Avm size (in bytes) on compile screen

### ISSUE THREAD

**Issue by igormcoelho** [NeoResearch/neocompiler-eco#52]
I think we need this: Calculate ScriptHash / Address / Avm size (in bytes) on compile screen

**Comment by vncoelho** [comment]
Done, broda.
Please check if the size is just the length. I think it is wrong. But, at least, the template is done.

**Comment by vncoelho** [comment]
https://github.com/NeoResearch/neocompiler-eco/commit/6d0da094e81f42d3fb08c42c96eb5a78249a5c9d

**Comment by igormcoelho** [comment]
Amazing work brother! Byte count is int( size / 2 ), so its showing double count now... but it's fine, easy to fix. Thanks a lot!

**Comment by vncoelho** [comment]
![image](https://user-images.githubusercontent.com/17395762/55022701-ec273200-4fd9-11e9-9057-07252166c6c6.png)

**Comment by igormcoelho** [comment]
Good. 124 should be 62 :P
