### ISSUE TITLE
RPC stats polling at one second intervals on TestNet and MainNet

### ISSUE THREAD

**Issue by hal0x2328** [NeoResearch/neocompiler-eco#53]
The node block height/version/mempool queries that populate the stats in the menu bar are each being polled once per second, which I understand is normal for the one-second-per-block neocompiler nodes, but this happens even when connected to a MainNet or TestNet node.

The code should be changed to be aware of the number of seconds per block on whichever network it is connected to and only poll at those intervals, in order to avoid overloading the public nodes with unnecessary queries.

**Comment by vncoelho** [comment]
Makes sense, Hal, we gonna update this asap.

**Comment by igormcoelho** [comment]
Makes sense, we can reduce it to 7 or 8 seconds... that's fine for that case.

**Comment by vncoelho** [comment]
Thanks for the suggestion, @hal0x2328.

**Comment by vncoelho** [comment]
You can also personalize it now! :dancer: 

Go to settings:

![image](https://user-images.githubusercontent.com/17395762/55280800-2dd11900-5309-11e9-88a5-58d5d20e16c0.png)
