### ISSUE TITLE
bug losing my contract on compiler screen

### ISSUE THREAD

**Issue by igormcoelho** [NeoResearch/neocompiler-eco#57]
Second time I write my contract on C# main screen... then I go to Conversors tab, go to "Disassembly" tool, and when I come back, my contract is gone! It becomes Hello World again.
Please let's try to fix this.

**Comment by vncoelho** [comment]
I saw this yesterday, there is a strange reload.
It should be something related with the new angular routes and some refreshing.

**Comment by vncoelho** [comment]
But it looks like it happens just one time.
