### ISSUE TITLE
MapExample.cs is not returning the right (format) value

### ISSUE THREAD

**Issue by yurigabrich** [NeoResearch/neocompiler-eco#63]
The notifications from `StorageMap` used to show the same values on the comments. Now, it looks like the number format has changed for some reason.

Sincerely, I don't remember what used to be shown in RPC output. It is currently returning `byte[]` as value format for the `.AsBigInteger()` method. I think the expected format should be `Integer`, shouldn't be?

A last note, the first time I've notice this behaviour was on June, 15th.

**Comment by igormcoelho** [comment]
Thanks for notifying the issue Yuri. In fact, `.AsBigInteger()` doesn't guarantee that the value will be converted, as this is just a high-level _type cast_. I think there's a function `.ToBigInteger()` that guarantees the conversion. You can try that.

**Comment by yurigabrich** [comment]
Thank you, @igormcoelho! `.ToBigInteger()` solves the problem.
Now the RPC output shows type `Integer` and the right format of the number.
