### ISSUE TITLE
Something wrong to generate gas

### ISSUE THREAD

**Issue by yurigabrich** [NeoResearch/neocompiler-eco#66]
It uses to happen on the "second" half of the day (at night on Brazil time zone).
No gas, no gain. :cry: But I'm enjoying a new book meanwhile. :relaxed:

---
![image](https://user-images.githubusercontent.com/20340831/61918743-e2cab980-af28-11e9-8b16-2fe3200c39ba.png)

**Comment by corollari** [comment]
Hmm, so the issue is that every day at some time the GAS is set to zero?
Seems that this problem could be related to the network reset that's performed periodically.

**Comment by vncoelho** [comment]
It is a bug with the docker or docker-compose. We already reported to them!
The docker has a bug that destroys its network when we repeteadly put dockers up and down.

In this sense, sometimes we manually reset the server. We have also an input box in the settings where you can ask for the reset with a password (but it is not yet completelly working, sometimes it fails).

**Comment by yurigabrich** [comment]
Thank you for the explanations. It is working fine now.

Are there something I can contribute to solve it?
Maybe I can try to set the restart when the wallet freeze. Or at least document this behaviour and what steps should be done to get it working again.

**Comment by vncoelho** [comment]
That would be great, Yuri.

I am also having problems with the server executing a nohup command. For some reason the express is not being able to restart the service correctly.

**Comment by vncoelho** [comment]
I fixed the nohup for resetting and also created a command for automatic claim when users try to deploy and invoke.

But we still need an automatic script for calling the `docker service restart` when the front-end detects such failures.

**Comment by yurigabrich** [comment]
Well done, @vncoelho! I've been noticing the automatic claim on last days and also the big increase on server availability time. Thanks for that!

I'd like to contribute for the docker restart issue but I don't know what it is about.

**Comment by vncoelho** [comment]
Perhaps it is much more stable now and resetting every 7 days.
The server has also been upgraded.
