### ISSUE TITLE
Issues with Compiler server and node

### ISSUE THREAD

**Issue by AncientMayar** [NeoResearch/neocompiler-eco#69]
Working with @igormcoelho  here at UERJ... Suggestion to install node on readme:
`sudo snap install --edge node --classic`

This installs bleeding edge node version (v13 today)

Install npm normally: `sudo apt install npm`

Update npm packages locally (specially `express` server):
`npm install`

**Comment by vncoelho** [comment]
Thanks @AncientMayar, precise descriptions!
