### ISSUE TITLE
Sync w2, w3, w4 and adjust message

### ISSUE THREAD

**Issue by vncoelho** [NeoResearch/neocompiler-eco#7]

**Comment by vncoelho** [comment]
Adjust relayed tx message at the end.

Sync w2, w3 and w4 by comparing self. wallet. height and default blockchain. 
Or... try to switch wallets on screen 5.
It would avoid extra waits for ocasional calls

**Comment by vncoelho** [comment]
Done.

**Comment by igormcoelho** [comment]
Ok brother, seems you did the job already.
