### ISSUE TITLE
[feature] Improve TXs responsive table

### ISSUE THREAD

**Issue by vncoelho** [NeoResearch/neocompiler-eco#8]
*Status are currently not working and could be updated when user calls a button, such as in the Utils for checking balances
*Create box for allowing users to insert TXs to be table by hand
*Future, change and modify transaction orders

**Comment by vncoelho** [comment]
*Status are now working

2. Box are still missing
3. Modify transactions orders is also a future feature

**Comment by FabioRick** [comment]
Table are now refreshing every 30s

**Comment by vncoelho** [comment]
Gud gud, @FabioRick. Thanks.
It is very nice now. Perhaps, we can change to 10s now, because of the higher speed of the network.

When all TX are already found we can stop refreshing to avoid spamming the server.

I do not know if it is very useful. However, in some cases someone may need to restore information from it. Letś see the future demands... :dagger:

**Comment by vncoelho** [comment]
Restore old transaction by clicking at the table
