### ISSUE TITLE
Submission of raw .avm

### ISSUE THREAD

**Issue by igormcoelho** [NeoResearch/neocompiler-eco#9]
It would be interesting to have a feature for submission of raw .avm file. That would simplify integration with VStudio and other Desktop IDEs, so advanced programmers won't need to setup their own NEO Ecosystem (besides the local compiler, if they have one already).

**Comment by vncoelho** [comment]
That is true, my brother.

With the rebrand to NeoCompiler Eco(system) and the features that @igormcoelho and @FabioRick have been implementing, many developers may want to skip the compiling part.

**Comment by igormcoelho** [comment]
@FabioRick  already implemented this feature: https://github.com/NeoResearch/neocompiler-eco/commit/fd163d67d328b7e1756859b2ef4efc1235c04507
